import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'pt' | 'en' | 'es' | 'nl' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    // Home page
    'home.title': 'Avaliação de Características do Espectro Autista',
    'home.subtitle': 'Uma ferramenta de autoconhecimento baseada em características comuns do espectro autista',
    'home.description': 'Este questionário foi desenvolvido para ajudar na identificação de características que podem estar relacionadas ao espectro autista. É importante lembrar que este teste é apenas para fins educacionais e de autoconhecimento.',
    'home.startButton': 'Iniciar Avaliação',
    'home.disclaimer': 'Importante: Este teste é apenas para entretenimento e autoconhecimento. Não substitui uma avaliação profissional.',
    'home.howItWorks': 'Como Funciona',
    'home.about': 'Sobre o Teste',
    
    // Assessment page
    'assessment.title': 'Avaliação de Características do Espectro Autista',
    'assessment.subtitle': 'Responda as questões de acordo com como você se identifica com cada afirmação. Lembre-se: este teste é apenas para autoconhecimento e entretenimento.',
    'assessment.question': 'Questão',
    'assessment.of': 'de',
    'assessment.back': 'Voltar',
    'assessment.previous': 'Anterior',
    'assessment.next': 'Próxima',
    'assessment.finish': 'Finalizar Avaliação',
    'assessment.backToHome': 'Voltar ao Início',
    
    // Results
    'results.title': 'Resultado da Avaliação',
    'results.subtitle': 'Análise baseada em suas respostas',
    'results.score': 'Pontuação',
    'results.downloadPdf': 'Baixar PDF',
    'results.retakeTest': 'Refazer Teste',
    'results.characteristics': 'Características identificadas:',
    'results.recommendation': 'Recomendação:',
    'results.important': 'Importante:',
    'results.disclaimer': 'Este teste é apenas para entretenimento e autoconhecimento. Não substitui uma avaliação profissional. Para um diagnóstico adequado, procure um profissional especializado em autismo.',
    
    // Response options
    'response.stronglyIdentify': 'Me identifico muito',
    'response.identify': 'Me identifico',
    'response.slightlyIdentify': 'Me identifico pouco',
    'response.dontIdentify': 'Não me identifico',
    
    // Language selector
    'language.selector': 'Idioma',
    'language.portuguese': 'Português (BR)',
    'language.english': 'English',
    'language.spanish': 'Español',
    'language.dutch': 'Nederlands',
    'language.german': 'Deutsch',
    
    // Questions in Portuguese
    'question.1': 'Em uma reunião de trabalho, seu colega faz uma piada que todos acham engraçada, mas você não entende por que é engraçado.',
    'question.2': 'Alguém diz "Você pode me dar uma mão?" enquanto carrega caixas pesadas.',
    'question.3': 'Um colega de trabalho menciona que teve uma "manhã difícil" com um leve sorriso.',
    'question.4': 'Durante uma conversa casual, alguém pergunta "Como foi seu fim de semana?"',
    'question.5': 'Seu amigo diz "Estou morrendo de vergonha" depois de um erro.',
    'question.6': 'Você está se sentindo estressado após um longo dia de trabalho/escola.',
    'question.7': 'Enquanto se concentra em uma tarefa, você se percebe batendo os dedos ritmicamente.',
    'question.8': 'Você precisa organizar seu espaço de trabalho.',
    'question.9': 'Ao caminhar por um piso ladrilhado, você nota o padrão.',
    'question.10': 'Você está esperando em uma fila longa.',
    'question.11': 'Você entra em um restaurante movimentado com luzes brilhantes, música alta e cheiros fortes de comida.',
    'question.12': 'Você precisa comprar roupas novas, mas a loja só tem itens feitos de um tecido que parece áspero.',
    'question.13': 'Alguém usando perfume forte se senta ao seu lado no transporte público.',
    'question.14': 'O alarme de incêndio dispara inesperadamente durante um simulacro.',
    'question.15': 'Oferecem-lhe comida com múltiplas texturas misturadas.',
    'question.16': 'Um amigo conta animadamente sobre seus planos de férias.',
    'question.17': 'Durante uma conversa, você nota a outra pessoa olhando para o relógio.',
    'question.18': 'Alguém compartilha que está se sentindo triste porque seu animal de estimação está doente.',
    'question.19': 'Em uma conversa em grupo, outros estão discutindo planos de fim de semana.',
    'question.20': 'Um colega menciona que está tendo dificuldades com um projeto.',
    'question.21': 'Sua rota usual para o trabalho está bloqueada devido à construção.',
    'question.22': 'Os planos para uma viagem de fim de semana são cancelados repentinamente.',
    'question.23': 'Sua cafeteria favorita fica sem seu pedido usual.',
    'question.24': 'Uma reunião é reagendada no último minuto.',
    'question.25': 'Seu assento usual no trabalho/escola é ocupado por outra pessoa.',
    'question.26': 'Você tem tempo livre no fim de semana.',
    'question.27': 'Alguém pergunta sobre seus interesses.',
    'question.28': 'Você está escolhendo um livro para ler.',
    'question.29': 'Planejando um destino de férias.',
    'question.30': 'Decorando seu espaço de vida.',
    'question.31': 'Durante conversas, fazer contato visual parece:',
    'question.32': 'Alguém acena para você do outro lado da sala.',
    'question.33': 'Ler expressões faciais em outros é:',
    'question.34': 'Usar gestos ao falar:',
    'question.35': 'O tom de alguém soa diferente de suas palavras.',
    'question.36': 'Iniciar um projeto de várias etapas:',
    'question.37': 'Gerenciar múltiplos prazos:',
    'question.38': 'Fazer as malas para uma viagem:',
    'question.39': 'Seguir instruções de várias partes:',
    'question.40': 'Alternar entre diferentes tarefas:',
    'question.41': 'Alguém diz "Quebre uma perna!" antes de sua apresentação.',
    'question.42': 'Ler "nas entrelinhas" em e-mails:',
    'question.43': 'Alguém diz "Isso é ótimo" em um tom monótono após más notícias.',
    'question.44': 'Entender metáforas na conversa:',
    'question.45': 'Alguém diz que está "nas nuvens".',
    'question.46': 'Um amigo cancela planos no último minuto.',
    'question.47': 'Alguém discorda da sua opinião.',
    'question.48': 'Prever como os outros vão reagir:',
    'question.49': 'Alguém não compartilha seu entusiasmo por um tópico.',
    'question.50': 'Entender por que alguém pode mentir para poupar sentimentos:',
    'question.51': 'Em uma festa, alguém que você não conhece bem começa a contar sobre seus problemas.',
    'question.52': 'Seu colega de trabalho parece chateado, mas não disse nada diretamente.',
    'question.53': 'Em um grupo, alguém faz uma piada sobre experiências compartilhadas das quais você não participou.',
    'question.54': 'Um amigo insinua que gostaria de ser convidado para seu evento.',
    'question.55': 'A linguagem corporal de alguém sugere que eles estão desconfortáveis com um tópico.',
    'question.56': 'Seu tempo de hobby de interesse especial é interrompido por um visitante inesperado.',
    'question.57': 'Você não consegue encontrar sua marca usual na loja, apenas alternativas.',
    'question.58': 'Seu fim de semana planejado de foco no seu interesse é interrompido por uma obrigação familiar.',
    'question.59': 'Uma loja se reorganiza, movendo seus itens de interesse especial para uma seção diferente.',
    'question.60': 'Sua rotina usual para desfrutar de seu interesse é impossível devido às circunstâncias.',
    'question.61': 'Em um espaço barulhento e lotado, você se sente sobrecarregado.',
    'question.62': 'As luzes fluorescentes em seu espaço de trabalho estão te incomodando.',
    'question.63': 'Textura de roupa desconfortável durante todo o dia.',
    'question.64': 'Múltiplos sons sobrepostos em seu ambiente.',
    'question.65': 'Cheiros fortes causam desconforto em um ambiente social.',
    'question.66': 'Pedido para explicar um projeto complexo que você está lutando para organizar.',
    'question.67': 'Precisa comunicar múltiplos atrasos de tarefas para sua equipe.',
    'question.68': 'Seguir uma conversa enquanto gerencia outros pensamentos.',
    'question.69': 'Planejar e explicar uma atividade em grupo.',
    'question.70': 'Responder a perguntas inesperadas em uma reunião.',
    'question.71': 'Seu amigo diz "Estou com tanta fome que poderia comer um cavalo" enquanto parece cansado.',
    'question.72': 'Em uma discussão em grupo, alguém faz um comentário sarcástico sobre o tempo.',
    'question.73': 'Um colega diz "Claro, empilhe mais trabalho em mim" com um sorriso forçado.',
    'question.74': 'Alguém conta uma mentira branca para evitar magoar os sentimentos de outro na sua frente.',
    'question.75': 'Um amigo exagera uma história para entretenimento em uma festa.',
    'question.76': 'Um museu sobre seu interesse especial tem luzes brilhantes e multidões.',
    'question.77': 'Seus itens relacionados ao interesse têm texturas que te incomodam.',
    'question.78': 'Uma convenção para seu interesse está em um local desafiador sensorialmente.',
    'question.79': 'Conteúdo online sobre seu interesse tem sons de reprodução automática.',
    'question.80': 'Seu interesse requer visitar lojas movimentadas e barulhentas.'
  },
  en: {
    // Home page
    'home.title': 'Autism Spectrum Characteristics Assessment',
    'home.subtitle': 'A self-awareness tool based on common autism spectrum characteristics',
    'home.description': 'This questionnaire was developed to help identify characteristics that may be related to the autism spectrum. It is important to remember that this test is for educational and self-awareness purposes only.',
    'home.startButton': 'Start Assessment',
    'home.disclaimer': 'Important: This test is for entertainment and self-awareness purposes only. It does not replace a professional evaluation.',
    'home.howItWorks': 'How It Works',
    'home.about': 'About the Test',
    
    // Assessment page
    'assessment.title': 'Autism Spectrum Characteristics Assessment',
    'assessment.subtitle': 'Answer the questions according to how much you identify with each statement. Remember: this test is for self-awareness and entertainment only.',
    'assessment.question': 'Question',
    'assessment.of': 'of',
    'assessment.back': 'Back',
    'assessment.previous': 'Previous',
    'assessment.next': 'Next',
    'assessment.finish': 'Finish Assessment',
    'assessment.backToHome': 'Back to Home',
    
    // Results
    'results.title': 'Assessment Results',
    'results.subtitle': 'Analysis based on your responses',
    'results.score': 'Score',
    'results.downloadPdf': 'Download PDF',
    'results.retakeTest': 'Retake Test',
    'results.characteristics': 'Identified characteristics:',
    'results.recommendation': 'Recommendation:',
    'results.important': 'Important:',
    'results.disclaimer': 'This test is for entertainment and self-awareness purposes only. It does not replace a professional evaluation. For proper diagnosis, seek a specialist in autism.',
    
    // Response options
    'response.stronglyIdentify': 'Strongly identify',
    'response.identify': 'Identify',
    'response.slightlyIdentify': 'Slightly identify',
    'response.dontIdentify': 'Don\'t identify',
    
    // Language selector
    'language.selector': 'Language',
    'language.portuguese': 'Português (BR)',
    'language.english': 'English',
    'language.spanish': 'Español',
    'language.dutch': 'Nederlands',
    'language.german': 'Deutsch',
    
    // Questions in English
    'question.1': 'At a work meeting, your colleague makes a joke that everyone laughs at, but you don\'t understand why it\'s funny.',
    'question.2': 'Someone says \'Can you give me a hand?\' while carrying heavy boxes.',
    'question.3': 'A coworker mentions they had a \'rough morning\' with a slight smile.',
    'question.4': 'During small talk, someone asks \'How was your weekend?\'',
    'question.5': 'Your friend says \'I\'m dying of embarrassment\' after a mistake.',
    'question.6': 'You\'re feeling stressed after a long day at work/school.',
    'question.7': 'While concentrating on a task, you notice yourself tapping your fingers rhythmically.',
    'question.8': 'You need to organize your workspace.',
    'question.9': 'When walking through a tiled floor, you notice the pattern.',
    'question.10': 'You\'re waiting in a long line.',
    'question.11': 'You enter a busy restaurant with bright lights, loud music, and strong food smells.',
    'question.12': 'You need to buy new clothes, but the store only has items made from a fabric that feels rough.',
    'question.13': 'Someone wearing strong perfume sits next to you on public transport.',
    'question.14': 'The fire alarm goes off unexpectedly during a drill.',
    'question.15': 'You\'re offered food with multiple mixed textures.',
    'question.16': 'A friend excitedly tells you about their vacation plans.',
    'question.17': 'During a conversation, you notice the other person looking at their watch.',
    'question.18': 'Someone shares that they\'re feeling sad about their pet being sick.',
    'question.19': 'In a group conversation, others are discussing weekend plans.',
    'question.20': 'A colleague mentions they\'re struggling with a project.',
    'question.21': 'Your usual route to work is blocked due to construction.',
    'question.22': 'Plans for a weekend trip are suddenly cancelled.',
    'question.23': 'Your favorite coffee shop runs out of your usual order.',
    'question.24': 'A meeting is rescheduled at the last minute.',
    'question.25': 'Your usual seat at work/school is taken by someone else.',
    'question.26': 'You have free time on the weekend.',
    'question.27': 'Someone asks about your interests.',
    'question.28': 'You\'re choosing a book to read.',
    'question.29': 'Planning a vacation destination.',
    'question.30': 'Decorating your living space.',
    'question.31': 'During conversations, making eye contact feels:',
    'question.32': 'Someone waves at you from across the room.',
    'question.33': 'Reading facial expressions in others is:',
    'question.34': 'Using gestures while speaking:',
    'question.35': 'Someone\'s tone sounds different than their words.',
    'question.36': 'Starting a multi-step project:',
    'question.37': 'Managing multiple deadlines:',
    'question.38': 'Packing for a trip:',
    'question.39': 'Following multi-part instructions:',
    'question.40': 'Switching between different tasks:',
    'question.41': 'Someone says \'Break a leg!\' before your presentation.',
    'question.42': 'Reading \'between the lines\' in emails:',
    'question.43': 'Someone says \'That\'s just great\' in a flat tone after bad news.',
    'question.44': 'Understanding metaphors in conversation:',
    'question.45': 'Someone says they\'re \'on cloud nine.\'',
    'question.46': 'A friend cancels plans at the last minute.',
    'question.47': 'Someone disagrees with your opinion.',
    'question.48': 'Predicting how others will react:',
    'question.49': 'Someone doesn\'t share your enthusiasm for a topic.',
    'question.50': 'Understanding why someone might lie to spare feelings:',
    'question.51': 'At a party, someone you don\'t know well starts telling you about their problems.',
    'question.52': 'Your coworker seems upset but hasn\'t said anything directly.',
    'question.53': 'In a group, someone makes a joke about shared experiences you weren\'t part of.',
    'question.54': 'A friend hints they\'d like to be invited to your event.',
    'question.55': 'Someone\'s body language suggests they\'re uncomfortable with a topic.',
    'question.56': 'Your special interest hobby time is interrupted by an unexpected visitor.',
    'question.57': 'You can\'t find your usual brand at the store, only alternatives.',
    'question.58': 'Your planned weekend of focusing on your interest is disrupted by a family obligation.',
    'question.59': 'A store reorganizes, moving your special interest items to a different section.',
    'question.60': 'Your usual routine for enjoying your interest is impossible due to circumstances.',
    'question.61': 'In a noisy, crowded space, you feel overwhelmed.',
    'question.62': 'Fluorescent lights in your workspace are bothering you.',
    'question.63': 'Uncomfortable clothing texture throughout the day.',
    'question.64': 'Multiple overlapping sounds in your environment.',
    'question.65': 'Strong smells trigger discomfort in a social setting.',
    'question.66': 'Asked to explain a complex project you\'re struggling to organize.',
    'question.67': 'Need to communicate multiple task delays to your team.',
    'question.68': 'Following a conversation while managing other thoughts.',
    'question.69': 'Planning and explaining a group activity.',
    'question.70': 'Responding to unexpected questions in a meeting.',
    'question.71': 'Your friend says \'I\'m so hungry I could eat a horse\' while looking tired.',
    'question.72': 'In a group discussion, someone makes a sarcastic comment about the weather.',
    'question.73': 'A colleague says \'Sure, pile more work on me\' with a strained smile.',
    'question.74': 'Someone tells a white lie to avoid hurting another\'s feelings in front of you.',
    'question.75': 'A friend exaggerates a story for entertainment at a party.',
    'question.76': 'A museum about your special interest has bright lights and crowds.',
    'question.77': 'Your interest-related items have textures that bother you.',
    'question.78': 'A convention for your interest is in a sensory-challenging venue.',
    'question.79': 'Online content about your interest has autoplay sounds.',
    'question.80': 'Your interest requires visiting busy, noisy stores.'
  },
  es: {
    // Home page
    'home.title': 'Evaluación de Características del Espectro Autista',
    'home.subtitle': 'Una herramienta de autoconocimiento basada en características comunes del espectro autista',
    'home.description': 'Este cuestionario fue desarrollado para ayudar en la identificación de características que pueden estar relacionadas con el espectro autista. Es importante recordar que este test es solo para fines educativos y de autoconocimiento.',
    'home.startButton': 'Iniciar Evaluación',
    'home.disclaimer': 'Importante: Este test es solo para entretenimiento y autoconocimiento. No sustituye una evaluación profesional.',
    'home.howItWorks': 'Cómo Funciona',
    'home.about': 'Sobre el Test',
    
    // Assessment page
    'assessment.title': 'Evaluación de Características del Espectro Autista',
    'assessment.subtitle': 'Responde las preguntas según cómo te identifies con cada afirmación. Recuerda: este test es solo para autoconocimiento y entretenimiento.',
    'assessment.question': 'Pregunta',
    'assessment.of': 'de',
    'assessment.back': 'Volver',
    'assessment.previous': 'Anterior',
    'assessment.next': 'Siguiente',
    'assessment.finish': 'Finalizar Evaluación',
    'assessment.backToHome': 'Volver al Inicio',
    
    // Results
    'results.title': 'Resultado de la Evaluación',
    'results.subtitle': 'Análisis basado en tus respuestas',
    'results.score': 'Puntuación',
    'results.downloadPdf': 'Descargar PDF',
    'results.retakeTest': 'Repetir Test',
    'results.characteristics': 'Características identificadas:',
    'results.recommendation': 'Recomendación:',
    'results.important': 'Importante:',
    'results.disclaimer': 'Este test es solo para entretenimiento y autoconocimiento. No sustituye una evaluación profesional. Para un diagnóstico adecuado, busca un especialista en autismo.',
    
    // Response options
    'response.stronglyIdentify': 'Me identifico mucho',
    'response.identify': 'Me identifico',
    'response.slightlyIdentify': 'Me identifico poco',
    'response.dontIdentify': 'No me identifico',
    
    // Language selector
    'language.selector': 'Idioma',
    'language.portuguese': 'Português (BR)',
    'language.english': 'English',
    'language.spanish': 'Español',
    'language.dutch': 'Nederlands',
    'language.german': 'Deutsch',
    
    // Questions in Spanish
    'question.1': 'En una reunión de trabajo, tu colega hace un chiste que todos encuentran gracioso, pero no entiendes por qué es divertido.',
    'question.2': 'Alguien dice "¿Puedes echarme una mano?" mientras carga cajas pesadas.',
    'question.3': 'Un compañero de trabajo menciona que tuvo una "mañana difícil" con una ligera sonrisa.',
    'question.4': 'Durante una charla casual, alguien pregunta "¿Cómo estuvo tu fin de semana?"',
    'question.5': 'Tu amigo dice "Me muero de vergüenza" después de un error.',
    'question.6': 'Te sientes estresado después de un largo día de trabajo/escuela.',
    'question.7': 'Mientras te concentras en una tarea, te das cuenta de que golpeas los dedos rítmicamente.',
    'question.8': 'Necesitas organizar tu espacio de trabajo.',
    'question.9': 'Al caminar por un suelo de baldosas, notas el patrón.',
    'question.10': 'Estás esperando en una fila larga.',
    'question.11': 'Entras en un restaurante concurrido con luces brillantes, música fuerte y olores fuertes de comida.',
    'question.12': 'Necesitas comprar ropa nueva, pero la tienda solo tiene artículos hechos de una tela que se siente áspera.',
    'question.13': 'Alguien que usa perfume fuerte se sienta a tu lado en el transporte público.',
    'question.14': 'La alarma de incendios se activa inesperadamente durante un simulacro.',
    'question.15': 'Te ofrecen comida con múltiples texturas mezcladas.',
    'question.16': 'Un amigo te cuenta emocionado sobre sus planes de vacaciones.',
    'question.17': 'Durante una conversación, notas que la otra persona mira su reloj.',
    'question.18': 'Alguien comparte que se siente triste porque su mascota está enferma.',
    'question.19': 'En una conversación grupal, otros están discutiendo planes de fin de semana.',
    'question.20': 'Un colega menciona que está luchando con un proyecto.',
    'question.21': 'Tu ruta habitual al trabajo está bloqueada debido a construcción.',
    'question.22': 'Los planes para un viaje de fin de semana se cancelan repentinamente.',
    'question.23': 'Tu cafetería favorita se queda sin tu pedido habitual.',
    'question.24': 'Una reunión se reprograma en el último minuto.',
    'question.25': 'Tu asiento habitual en el trabajo/escuela es ocupado por otra persona.',
    'question.26': 'Tienes tiempo libre en el fin de semana.',
    'question.27': 'Alguien pregunta sobre tus intereses.',
    'question.28': 'Estás eligiendo un libro para leer.',
    'question.29': 'Planificando un destino de vacaciones.',
    'question.30': 'Decorando tu espacio vital.',
    'question.31': 'Durante conversaciones, hacer contacto visual se siente:',
    'question.32': 'Alguien te saluda desde el otro lado de la habitación.',
    'question.33': 'Leer expresiones faciales en otros es:',
    'question.34': 'Usar gestos al hablar:',
    'question.35': 'El tono de alguien suena diferente a sus palabras.',
    'question.36': 'Comenzar un proyecto de múltiples pasos:',
    'question.37': 'Gestionar múltiples plazos:',
    'question.38': 'Hacer las maletas para un viaje:',
    'question.39': 'Seguir instrucciones de múltiples partes:',
    'question.40': 'Cambiar entre diferentes tareas:',
    'question.41': 'Alguien dice "¡Rómpete una pierna!" antes de tu presentación.',
    'question.42': 'Leer "entre líneas" en emails:',
    'question.43': 'Alguien dice "Eso es genial" en un tono plano después de malas noticias.',
    'question.44': 'Entender metáforas en conversación:',
    'question.45': 'Alguien dice que está "en las nubes".',
    'question.46': 'Un amigo cancela planes en el último minuto.',
    'question.47': 'Alguien no está de acuerdo con tu opinión.',
    'question.48': 'Predecir cómo otros van a reaccionar:',
    'question.49': 'Alguien no comparte tu entusiasmo por un tema.',
    'question.50': 'Entender por qué alguien puede mentir para no herir sentimientos:',
    'question.51': 'En una fiesta, alguien que no conoces bien comienza a contarte sobre sus problemas.',
    'question.52': 'Tu compañero de trabajo parece molesto pero no ha dicho nada directamente.',
    'question.53': 'En un grupo, alguien hace un chiste sobre experiencias compartidas de las que no fuiste parte.',
    'question.54': 'Un amigo insinúa que le gustaría ser invitado a tu evento.',
    'question.55': 'El lenguaje corporal de alguien sugiere que están incómodos con un tema.',
    'question.56': 'Tu tiempo de hobby de interés especial es interrumpido por un visitante inesperado.',
    'question.57': 'No puedes encontrar tu marca habitual en la tienda, solo alternativas.',
    'question.58': 'Tu fin de semana planeado de enfocarte en tu interés es interrumpido por una obligación familiar.',
    'question.59': 'Una tienda se reorganiza, moviendo tus artículos de interés especial a una sección diferente.',
    'question.60': 'Tu rutina habitual para disfrutar de tu interés es imposible debido a las circunstancias.',
    'question.61': 'En un espacio ruidoso y abarrotado, te sientes abrumado.',
    'question.62': 'Las luces fluorescentes en tu espacio de trabajo te molestan.',
    'question.63': 'Textura de ropa incómoda durante todo el día.',
    'question.64': 'Múltiples sonidos superpuestos en tu ambiente.',
    'question.65': 'Los olores fuertes causan incomodidad en un entorno social.',
    'question.66': 'Te piden explicar un proyecto complejo que estás luchando por organizar.',
    'question.67': 'Necesitas comunicar múltiples retrasos de tareas a tu equipo.',
    'question.68': 'Seguir una conversación mientras gestionas otros pensamientos.',
    'question.69': 'Planificar y explicar una actividad grupal.',
    'question.70': 'Responder a preguntas inesperadas en una reunión.',
    'question.71': 'Tu amigo dice "Tengo tanta hambre que podría comerme un caballo" mientras parece cansado.',
    'question.72': 'En una discusión grupal, alguien hace un comentario sarcástico sobre el clima.',
    'question.73': 'Un colega dice "Claro, échame más trabajo encima" con una sonrisa forzada.',
    'question.74': 'Alguien dice una mentira piadosa para evitar herir los sentimientos de otro frente a ti.',
    'question.75': 'Un amigo exagera una historia para entretenimiento en una fiesta.',
    'question.76': 'Un museo sobre tu interés especial tiene luces brillantes y multitudes.',
    'question.77': 'Tus artículos relacionados con el interés tienen texturas que te molestan.',
    'question.78': 'Una convención para tu interés está en un lugar desafiante sensorialmente.',
    'question.79': 'El contenido en línea sobre tu interés tiene sonidos de reproducción automática.',
    'question.80': 'Tu interés requiere visitar tiendas concurridas y ruidosas.'
  },
  nl: {
    // Home page
    'home.title': 'Autismespectrum Kenmerken Beoordeling',
    'home.subtitle': 'Een zelfbewustzijn tool gebaseerd op veelvoorkomende autismespectrum kenmerken',
    'home.description': 'Deze vragenlijst is ontwikkeld om kenmerken te helpen identificeren die gerelateerd kunnen zijn aan het autismespectrum. Het is belangrijk om te onthouden dat deze test alleen is voor educatieve en zelfbewustzijn doeleinden.',
    'home.startButton': 'Start Beoordeling',
    'home.disclaimer': 'Belangrijk: Deze test is alleen voor entertainment en zelfbewustzijn doeleinden. Het vervangt geen professionele evaluatie.',
    'home.howItWorks': 'Hoe Het Werkt',
    'home.about': 'Over de Test',
    
    // Assessment page
    'assessment.title': 'Autismespectrum Kenmerken Beoordeling',
    'assessment.subtitle': 'Beantwoord de vragen volgens hoeveel je je identificeert met elke stelling. Onthoud: deze test is alleen voor zelfbewustzijn en entertainment.',
    'assessment.question': 'Vraag',
    'assessment.of': 'van',
    'assessment.back': 'Terug',
    'assessment.previous': 'Vorige',
    'assessment.next': 'Volgende',
    'assessment.finish': 'Beoordeling Voltooien',
    'assessment.backToHome': 'Terug naar Home',
    
    // Results
    'results.title': 'Beoordeling Resultaten',
    'results.subtitle': 'Analyse gebaseerd op je antwoorden',
    'results.score': 'Score',
    'results.downloadPdf': 'PDF Downloaden',
    'results.retakeTest': 'Test Opnieuw Doen',
    'results.characteristics': 'Geïdentificeerde kenmerken:',
    'results.recommendation': 'Aanbeveling:',
    'results.important': 'Belangrijk:',
    'results.disclaimer': 'Deze test is alleen voor entertainment en zelfbewustzijn doeleinden. Het vervangt geen professionele evaluatie. Voor een juiste diagnose, zoek een specialist in autisme.',
    
    // Response options
    'response.stronglyIdentify': 'Identificeer sterk',
    'response.identify': 'Identificeer',
    'response.slightlyIdentify': 'Identificeer enigszins',
    'response.dontIdentify': 'Identificeer niet',
    
    // Language selector
    'language.selector': 'Taal',
    'language.portuguese': 'Português (BR)',
    'language.english': 'English',
    'language.spanish': 'Español',
    'language.dutch': 'Nederlands',
    'language.german': 'Deutsch',
    
    // Questions in Dutch
    'question.1': 'Op een werkvergadering maakt je collega een grap waar iedereen om lacht, maar je begrijpt niet waarom het grappig is.',
    'question.2': 'Iemand zegt "Kun je me een handje helpen?" terwijl ze zware dozen dragen.',
    'question.3': 'Een collega vermeldt dat ze een "zware ochtend" hadden met een lichte glimlach.',
    'question.4': 'Tijdens small talk vraagt iemand "Hoe was je weekend?"',
    'question.5': 'Je vriend zegt "Ik sterf van schaamte" na een fout.',
    'question.6': 'Je voelt je gestrest na een lange dag op werk/school.',
    'question.7': 'Terwijl je je concentreert op een taak, merk je dat je ritmisch met je vingers tikt.',
    'question.8': 'Je moet je werkruimte organiseren.',
    'question.9': 'Bij het lopen over een betegelde vloer, merk je het patroon op.',
    'question.10': 'Je wacht in een lange rij.',
    'question.11': 'Je komt een druk restaurant binnen met felle lichten, luide muziek en sterke voedselgeuren.',
    'question.12': 'Je moet nieuwe kleren kopen, maar de winkel heeft alleen items gemaakt van een stof die ruw aanvoelt.',
    'question.13': 'Iemand met sterke parfum gaat naast je zitten in het openbaar vervoer.',
    'question.14': 'Het brandalarm gaat onverwacht af tijdens een oefening.',
    'question.15': 'Je krijgt voedsel aangeboden met meerdere gemengde texturen.',
    'question.16': 'Een vriend vertelt je enthousiast over hun vakantieplannen.',
    'question.17': 'Tijdens een gesprek merk je dat de andere persoon naar hun horloge kijkt.',
    'question.18': 'Iemand deelt dat ze zich verdrietig voelen omdat hun huisdier ziek is.',
    'question.19': 'In een groepsgesprek bespreken anderen weekendplannen.',
    'question.20': 'Een collega vermeldt dat ze worstelen met een project.',
    'question.21': 'Je gebruikelijke route naar werk is geblokkeerd door constructie.',
    'question.22': 'Plannen voor een weekendtrip worden plotseling geannuleerd.',
    'question.23': 'Je favoriete coffeeshop is uit je gebruikelijke bestelling.',
    'question.24': 'Een vergadering wordt op het laatste moment opnieuw gepland.',
    'question.25': 'Je gebruikelijke stoel op werk/school wordt ingenomen door iemand anders.',
    'question.26': 'Je hebt vrije tijd in het weekend.',
    'question.27': 'Iemand vraagt naar je interesses.',
    'question.28': 'Je kiest een boek om te lezen.',
    'question.29': 'Een vakantiebestemming plannen.',
    'question.30': 'Je leefruimte decoreren.',
    'question.31': 'Tijdens gesprekken voelt oogcontact maken:',
    'question.32': 'Iemand zwaait naar je vanaf de andere kant van de kamer.',
    'question.33': 'Gezichtsuitdrukkingen lezen bij anderen is:',
    'question.34': 'Gebaren gebruiken tijdens het spreken:',
    'question.35': 'Iemands toon klinkt anders dan hun woorden.',
    'question.36': 'Een project met meerdere stappen starten:',
    'question.37': 'Meerdere deadlines beheren:',
    'question.38': 'Inpakken voor een reis:',
    'question.39': 'Instructies met meerdere delen volgen:',
    'question.40': 'Schakelen tussen verschillende taken:',
    'question.41': 'Iemand zegt "Breek een been!" voor je presentatie.',
    'question.42': 'Tussen de regels door lezen in emails:',
    'question.43': 'Iemand zegt "Dat is geweldig" in een vlakke toon na slecht nieuws.',
    'question.44': 'Metaforen begrijpen in gesprek:',
    'question.45': 'Iemand zegt dat ze "op wolkje zeven" zijn.',
    'question.46': 'Een vriend annuleert plannen op het laatste moment.',
    'question.47': 'Iemand is het oneens met je mening.',
    'question.48': 'Voorspellen hoe anderen zullen reageren:',
    'question.49': 'Iemand deelt je enthousiasme voor een onderwerp niet.',
    'question.50': 'Begrijpen waarom iemand zou liegen om gevoelens te sparen:',
    'question.51': 'Op een feest begint iemand die je niet goed kent je over hun problemen te vertellen.',
    'question.52': 'Je collega lijkt van streek maar heeft niets direct gezegd.',
    'question.53': 'In een groep maakt iemand een grap over gedeelde ervaringen waar jij geen deel van uitmaakte.',
    'question.54': 'Een vriend hint dat ze graag uitgenodigd zouden worden voor je evenement.',
    'question.55': 'Iemands lichaamstaal suggereert dat ze ongemakkelijk zijn met een onderwerp.',
    'question.56': 'Je speciale interesse hobby tijd wordt onderbroken door een onverwachte bezoeker.',
    'question.57': 'Je kunt je gebruikelijke merk niet vinden in de winkel, alleen alternatieven.',
    'question.58': 'Je geplande weekend van focussen op je interesse wordt verstoord door een familieverplichting.',
    'question.59': 'Een winkel reorganiseert, waarbij je speciale interesse items naar een andere sectie worden verplaatst.',
    'question.60': 'Je gebruikelijke routine voor het genieten van je interesse is onmogelijk door omstandigheden.',
    'question.61': 'In een lawaaierige, drukke ruimte voel je je overweldigd.',
    'question.62': 'Fluorescerende lampen in je werkruimte storen je.',
    'question.63': 'Ongemakkelijke kledingstructuur de hele dag.',
    'question.64': 'Meerdere overlappende geluiden in je omgeving.',
    'question.65': 'Sterke geuren veroorzaken ongemak in een sociale omgeving.',
    'question.66': 'Gevraagd om een complex project uit te leggen dat je moeilijk kunt organiseren.',
    'question.67': 'Meerdere taakvertragingen moeten communiceren naar je team.',
    'question.68': 'Een gesprek volgen terwijl je andere gedachten beheert.',
    'question.69': 'Een groepsactiviteit plannen en uitleggen.',
    'question.70': 'Reageren op onverwachte vragen in een vergadering.',
    'question.71': 'Je vriend zegt "Ik heb zo\'n honger dat ik een paard zou kunnen opeten" terwijl ze er moe uitzien.',
    'question.72': 'In een groepsdiscussie maakt iemand een sarcastische opmerking over het weer.',
    'question.73': 'Een collega zegt "Natuurlijk, stapel meer werk op mij" met een geforceerde glimlach.',
    'question.74': 'Iemand vertelt een witte leugen om te voorkomen dat ze andermans gevoelens kwetsen voor jou.',
    'question.75': 'Een vriend overdrijft een verhaal voor entertainment op een feest.',
    'question.76': 'Een museum over je speciale interesse heeft felle lichten en menigten.',
    'question.77': 'Je interesse-gerelateerde items hebben texturen die je storen.',
    'question.78': 'Een conventie voor je interesse is in een sensorisch uitdagende locatie.',
    'question.79': 'Online content over je interesse heeft autoplay geluiden.',
    'question.80': 'Je interesse vereist het bezoeken van drukke, lawaaierige winkels.'
  },
  de: {
    // Home page
    'home.title': 'Autismus-Spektrum-Eigenschaften Bewertung',
    'home.subtitle': 'Ein Selbstbewusstsein-Tool basierend auf häufigen Autismus-Spektrum-Eigenschaften',
    'home.description': 'Dieser Fragebogen wurde entwickelt, um bei der Identifizierung von Eigenschaften zu helfen, die mit dem Autismus-Spektrum zusammenhängen könnten. Es ist wichtig zu bedenken, dass dieser Test nur für Bildungs- und Selbstbewusstseinszwecke ist.',
    'home.startButton': 'Bewertung Starten',
    'home.disclaimer': 'Wichtig: Dieser Test ist nur für Unterhaltungs- und Selbstbewusstseinszwecke. Er ersetzt keine professionelle Bewertung.',
    'home.howItWorks': 'Wie Es Funktioniert',
    'home.about': 'Über den Test',
    
    // Assessment page
    'assessment.title': 'Autismus-Spektrum-Eigenschaften Bewertung',
    'assessment.subtitle': 'Beantworte die Fragen entsprechend dem, wie sehr du dich mit jeder Aussage identifizierst. Denke daran: Dieser Test ist nur für Selbstbewusstsein und Unterhaltung.',
    'assessment.question': 'Frage',
    'assessment.of': 'von',
    'assessment.back': 'Zurück',
    'assessment.previous': 'Vorherige',
    'assessment.next': 'Nächste',
    'assessment.finish': 'Bewertung Abschließen',
    'assessment.backToHome': 'Zurück zur Startseite',
    
    // Results
    'results.title': 'Bewertungsergebnisse',
    'results.subtitle': 'Analyse basierend auf deinen Antworten',
    'results.score': 'Punktzahl',
    'results.downloadPdf': 'PDF Herunterladen',
    'results.retakeTest': 'Test Wiederholen',
    'results.characteristics': 'Identifizierte Eigenschaften:',
    'results.recommendation': 'Empfehlung:',
    'results.important': 'Wichtig:',
    'results.disclaimer': 'Dieser Test ist nur für Unterhaltungs- und Selbstbewusstseinszwecke. Er ersetzt keine professionelle Bewertung. Für eine ordnungsgemäße Diagnose suche einen Spezialisten für Autismus.',
    
    // Response options
    'response.stronglyIdentify': 'Identifiziere mich stark',
    'response.identify': 'Identifiziere mich',
    'response.slightlyIdentify': 'Identifiziere mich etwas',
    'response.dontIdentify': 'Identifiziere mich nicht',
    
    // Language selector
    'language.selector': 'Sprache',
    'language.portuguese': 'Português (BR)',
    'language.english': 'English',
    'language.spanish': 'Español',
    'language.dutch': 'Nederlands',
    'language.german': 'Deutsch',
    
    // Questions in German
    'question.1': 'Bei einem Arbeitstreffen macht dein Kollege einen Scherz, über den alle lachen, aber du verstehst nicht, warum er lustig ist.',
    'question.2': 'Jemand sagt "Kannst du mir helfen?" während er schwere Kisten trägt.',
    'question.3': 'Ein Arbeitskollege erwähnt, dass er einen "schweren Morgen" hatte mit einem leichten Lächeln.',
    'question.4': 'Während Small Talk fragt jemand "Wie war dein Wochenende?"',
    'question.5': 'Dein Freund sagt "Ich sterbe vor Scham" nach einem Fehler.',
    'question.6': 'Du fühlst dich gestresst nach einem langen Tag bei der Arbeit/Schule.',
    'question.7': 'Während du dich auf eine Aufgabe konzentrierst, bemerkst du, dass du rhythmisch mit den Fingern klopfst.',
    'question.8': 'Du musst deinen Arbeitsplatz organisieren.',
    'question.9': 'Beim Gehen über einen gefliesten Boden bemerkst du das Muster.',
    'question.10': 'Du wartest in einer langen Schlange.',
    'question.11': 'Du betrittst ein geschäftiges Restaurant mit hellen Lichtern, lauter Musik und starken Essensgerüchen.',
    'question.12': 'Du musst neue Kleidung kaufen, aber der Laden hat nur Artikel aus einem Stoff, der sich rau anfühlt.',
    'question.13': 'Jemand mit starkem Parfüm setzt sich neben dich in öffentlichen Verkehrsmitteln.',
    'question.14': 'Der Feueralarm geht unerwartet während einer Übung los.',
    'question.15': 'Dir wird Essen mit mehreren gemischten Texturen angeboten.',
    'question.16': 'Ein Freund erzählt dir aufgeregt von seinen Urlaubsplänen.',
    'question.17': 'Während eines Gesprächs bemerkst du, dass die andere Person auf ihre Uhr schaut.',
    'question.18': 'Jemand teilt mit, dass er sich traurig fühlt, weil sein Haustier krank ist.',
    'question.19': 'In einem Gruppengespräch diskutieren andere über Wochenendpläne.',
    'question.20': 'Ein Kollege erwähnt, dass er mit einem Projekt kämpft.',
    'question.21': 'Deine übliche Route zur Arbeit ist wegen Bauarbeiten blockiert.',
    'question.22': 'Pläne für eine Wochenendreise werden plötzlich abgesagt.',
    'question.23': 'Dein liebstes Café hat deine übliche Bestellung nicht vorrätig.',
    'question.24': 'Ein Meeting wird in letzter Minute verschoben.',
    'question.25': 'Dein üblicher Platz bei der Arbeit/Schule wird von jemand anderem eingenommen.',
    'question.26': 'Du hast freie Zeit am Wochenende.',
    'question.27': 'Jemand fragt nach deinen Interessen.',
    'question.28': 'Du wählst ein Buch zum Lesen aus.',
    'question.29': 'Ein Urlaubsziel planen.',
    'question.30': 'Deinen Wohnraum dekorieren.',
    'question.31': 'Während Gesprächen fühlt sich Augenkontakt herstellen an:',
    'question.32': 'Jemand winkt dir von der anderen Seite des Raumes zu.',
    'question.33': 'Gesichtsausdrücke bei anderen zu lesen ist:',
    'question.34': 'Gesten beim Sprechen verwenden:',
    'question.35': 'Jemandes Ton klingt anders als ihre Worte.',
    'question.36': 'Ein mehrstufiges Projekt beginnen:',
    'question.37': 'Mehrere Fristen verwalten:',
    'question.38': 'Für eine Reise packen:',
    'question.39': 'Mehrteilige Anweisungen befolgen:',
    'question.40': 'Zwischen verschiedenen Aufgaben wechseln:',
    'question.41': 'Jemand sagt "Hals- und Beinbruch!" vor deiner Präsentation.',
    'question.42': 'Zwischen den Zeilen lesen in E-Mails:',
    'question.43': 'Jemand sagt "Das ist ja toll" in einem flachen Ton nach schlechten Nachrichten.',
    'question.44': 'Metaphern im Gespräch verstehen:',
    'question.45': 'Jemand sagt, er ist "auf Wolke sieben".',
    'question.46': 'Ein Freund sagt Pläne in letzter Minute ab.',
    'question.47': 'Jemand stimmt deiner Meinung nicht zu.',
    'question.48': 'Vorhersagen, wie andere reagieren werden:',
    'question.49': 'Jemand teilt deine Begeisterung für ein Thema nicht.',
    'question.50': 'Verstehen, warum jemand lügen könnte, um Gefühle zu schonen:',
    'question.51': 'Auf einer Party beginnt jemand, den du nicht gut kennst, dir von seinen Problemen zu erzählen.',
    'question.52': 'Dein Arbeitskollege scheint verärgert, hat aber nichts direkt gesagt.',
    'question.53': 'In einer Gruppe macht jemand einen Scherz über gemeinsame Erfahrungen, an denen du nicht teilgenommen hast.',
    'question.54': 'Ein Freund deutet an, dass er gerne zu deinem Event eingeladen werden möchte.',
    'question.55': 'Jemandes Körpersprache deutet darauf hin, dass er sich bei einem Thema unwohl fühlt.',
    'question.56': 'Deine spezielle Interesse-Hobby-Zeit wird von einem unerwarteten Besucher unterbrochen.',
    'question.57': 'Du kannst deine übliche Marke im Laden nicht finden, nur Alternativen.',
    'question.58': 'Dein geplantes Wochenende, dich auf dein Interesse zu konzentrieren, wird durch eine Familienverpflichtung gestört.',
    'question.59': 'Ein Laden reorganisiert sich und verlegt deine speziellen Interesse-Artikel in einen anderen Bereich.',
    'question.60': 'Deine übliche Routine, dein Interesse zu genießen, ist aufgrund der Umstände unmöglich.',
    'question.61': 'In einem lauten, überfüllten Raum fühlst du dich überwältigt.',
    'question.62': 'Leuchtstofflampen in deinem Arbeitsbereich stören dich.',
    'question.63': 'Unbequeme Kleidungstextur den ganzen Tag.',
    'question.64': 'Mehrere sich überlappende Geräusche in deiner Umgebung.',
    'question.65': 'Starke Gerüche verursachen Unbehagen in einer sozialen Umgebung.',
    'question.66': 'Gebeten, ein komplexes Projekt zu erklären, das du zu organisieren kämpfst.',
    'question.67': 'Mehrere Aufgabenverzögerungen an dein Team kommunizieren müssen.',
    'question.68': 'Einem Gespräch folgen, während du andere Gedanken managst.',
    'question.69': 'Eine Gruppenaktivität planen und erklären.',
    'question.70': 'Auf unerwartete Fragen in einem Meeting antworten.',
    'question.71': 'Dein Freund sagt "Ich bin so hungrig, ich könnte ein Pferd essen" während er müde aussieht.',
    'question.72': 'In einer Gruppendiskussion macht jemand einen sarkastischen Kommentar über das Wetter.',
    'question.73': 'Ein Kollege sagt "Klar, häuf mir mehr Arbeit auf" mit einem angestrengten Lächeln.',
    'question.74': 'Jemand erzählt eine Notlüge, um zu vermeiden, die Gefühle eines anderen vor dir zu verletzen.',
    'question.75': 'Ein Freund übertreibt eine Geschichte zur Unterhaltung auf einer Party.',
    'question.76': 'Ein Museum über dein spezielles Interesse hat helle Lichter und Menschenmengen.',
    'question.77': 'Deine interessenbezogenen Gegenstände haben Texturen, die dich stören.',
    'question.78': 'Eine Konvention für dein Interesse findet an einem sensorisch herausfordernden Ort statt.',
    'question.79': 'Online-Inhalte über dein Interesse haben Autoplay-Sounds.',
    'question.80': 'Dein Interesse erfordert den Besuch geschäftiger, lauter Geschäfte.'
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'pt';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};